---
# handlers file for kvm

- name: update initramfs
  shell: update-initramfs -u

- name: update grub
  shell: update-grub

- name: restart libvirtd
  service:
    name: libvirtd
    state: restarted

